//taskControllers.js
 
import * as TaskModel from '../models/task.model.js';


// ---------------------
// GET all tasks
// ---------------------
export const getTasks = async (req, res) => {
    try {
        const tasks = await TaskModel.getAll();
        res.json(tasks);
    } catch (err) {
        res.status(500).json({ error: "Failed to fetch tasks from MariaDB" });
    }
};

// ---------------------
// GET task by id
// ---------------------
export const getTaskById = async (req, res) => {
    try {
        const taskId = parseInt(req.params.id);
        const task = await TaskModel.getById(taskId);

        if (!task) {
            return res.status(404).json({ error: "Task not found in database" });
        }
        res.json(task);
    } catch (err) {
        res.status(500).json({ error: "Error retrieving task" });
    }
};

// ---------------------
// POST create task
// ---------------------
export const createTask = async (req, res) => {
    try {
        const { title } = req.body;
        if (!title) return res.status(400).json({ error: "Title is required" });

        const result = await TaskModel.create({ title });
        // result.insertId is the ID generated by MariaDB auto-increment
        res.status(201).json({ id: Number(result.insertId), title });
    } catch (err) {
        res.status(500).json({ error: "Could not persist new task" });
    }
};

// ---------------------
// PUT replace task (Full Update)
// ---------------------
export const replaceTask = async (req, res) => {
    try {
        const taskId = parseInt(req.params.id);
        const { title } = req.body;

        const result = await TaskModel.update(taskId, { title });

        if (result.affectedRows === 0) {
            return res.status(404).json({ error: "Task not found" });
        }
        res.json({ id: taskId, title });
    } catch (err) {
        res.status(500).json({ error: "Update failed" });
    }
};

// ---------------------
// PATCH update task (Partial Update)
// ---------------------
export const updateTask = async (req, res) => {
    try {
        const taskId = parseInt(req.params.id);
        // For a simple task, PATCH and PUT often look similar, 
        // but here we check if the title was actually provided.
        if (!req.body.title) {
            return res.status(400).json({ error: "No fields provided to update" });
        }

        await TaskModel.update(taskId, req.body);
        res.json({ message: "Task patched successfully" });
    } catch (err) {
        res.status(500).json({ error: "Patch failed" });
    }
};

// ---------------------
// DELETE task
// ---------------------
export const deleteTask = async (req, res) => {
    try {
        const taskId = parseInt(req.params.id);
        const result = await TaskModel.remove(taskId);

        if (result.affectedRows === 0) {
            return res.status(404).json({ error: "Task not found" });
        }
        res.json({ message: "Task deleted from MariaDB" });
    } catch (err) {
        res.status(500).json({ error: "Delete operation failed" });
    }
};

// ---------------------
// HEAD request
// ---------------------
export const headTasks = async (req, res) => {
    try {
        const tasks = await TaskModel.getAll();
        res.set("X-Total-Tasks", tasks.length);
        res.status(200).end();
    } catch (err) {
        res.status(500).end();
    }
};

// ---------------------
// OPTIONS request
// ---------------------
export const optionsTasks = (req, res) => {
    res.set("Allow", "GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS");
    res.sendStatus(200);
};